### ISSUE TITLE
Need help regarding collision of ids

### ISSUE THREAD

**Issue by dnmahendra** [ericelliott/cuid#102]
![screen shot 2018-04-10 at 2 22 00 pm](https://user-images.githubusercontent.com/15628503/38536102-ad9e7c46-3cca-11e8-800f-ad53474410de.png)

I am using this package to generate impression_ids for the products listed on the website pages. These impressions are getting stored in the database. The above screenshot shows for the same device_id at different times on different pages there is collision of ids happening. 

Can I get any advise regarding this?

**Comment by ericelliott** [comment]
Sometimes people see things like this as the result of bugs in the software, rather than duplicate ids being generated. For example, a record may be generated, and an ID is stored in some shared mutable state.

The timestamp in the id is identical to the millisecond, suggesting that the two ids were generated in the same millisecond. Also, the host fingerprints are identical, and the instance counter is identical.

The only way that's possible is if they were generated during the same millisecond on the same host, and _both the first id issued by the software instance running cuid_.

Things to check:

* Are your system clocks working, and synced with real time?
* Do each of your id-generating hosts create unique fingerprints?
* Are ids stored in any shared mutable state? Is it possible that an id generated a single time is being shared between more than one record?

Do some digging, if you can supply some code that reproduces the problem and show that it's a problem with cuid, please reopen this issue.
