### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by ghost** [ericelliott/cuid#13]
Can I get the timestamp from the generated id?

**Comment by Cicko** [comment]
@ericelliott How can I find the algorithm to get the date from the cuid? 

From what I see from the README it says that the first 8 characters after the letter 'c' is the timestamp, but how can I convert it to an actual date?

And why you don't recommend it?

Thanks in advance

**Comment by ericelliott** [comment]
As explained above, and in the documentation, you don't. If you need to know the time something was created, record a separate timestamp. Ids should only be used as ids, and the cuid spec was not designed for data extraction. Groupings do not have guaranteed lengths.

**Comment by ericelliott** [comment]
The security risk associated with extracting metadata from ids is the reason CUID is deprecated and we now prefer [CUID2](https://github.com/paralleldrive/cuid2?tab=readme-ov-file#cuid2).

**Comment by Cicko** [comment]
@ericelliott Thank you for your answer. 

I asked because in our project we just added a field `createdAt` in our PostgresSQL recently and we set a default value of '1999-12-31 23:59:59.000' so all older tuples in the DB have this value which is unrealistic and I thought by running another migration and decode the id (which is a cuid) could at least populate a correct `createdAt` value.
