### ISSUE TITLE
slug() is generating 7 character IDs

### ISSUE THREAD

**Issue by powmedia** [ericelliott/cuid#16]
The documentation states that IDs generated through cuid.slug() weigh in at 8 characters, however the ones I'm seeing are 7 characters.  Is this expected behaviour?  Does the documentation mean they will be _up to_ 8 characters?

**Comment by ericelliott** [comment]
Length is not guaranteed.

**Comment by MarkHerhold** [comment]
@ericelliott Could you explain what part of the cuid slug may vary in length? I'm wondering if this would affect the alphanumeric sortability of slugs.

**Comment by MarkHerhold** [comment]
To answer my own question, the counter portion of the slug grows unboundedly, which is why there is no guarantee on length.

The 2-character date representation comes before the counter, so I'd consider the resulting records well sortable across instances when generating IDs every few milliseconds. For anyone reading this, please note that I am no statistician. :)

**Comment by ericelliott** [comment]
Want to submit a PR?

**Comment by MarkHerhold** [comment]
@ericelliott for what? I'm OK with the slug growing unbounded mostly because I don't have a better strategy for keeping everything short while maintaining a reasonable guarantee of uniqueness.

Or did you mean a docs update? :) I can do this tomorrow.

**Comment by ericelliott** [comment]
Docs would be fine. =)

**Comment by MarkHerhold** [comment]
I ran into this again and did re-investigated the code (I am running a SQL DB with fixed column lengths). It turns out that my previous conclusion that the slug grows unboundedly is incorrect. :confused:

The actual max slug length is 10 characters as the counter will only ever contribute a max of 4 characters to the slug length. Therefore, slugs range for 7 - 10 chars. I'll update the README. Sorry about this!
