### ISSUE TITLE
Can we provide a bower module for this please?

### ISSUE THREAD

**Issue by volkovasystems** [ericelliott/cuid#76]

**Comment by ericelliott** [comment]
Try `bower install cuid`.

We no longer advertise Bower support because Bower is obsolete. It is no longer actively maintained, and you should try to migrate your codebase to use ES6 modules with something like Webpack as soon as possible.

**Comment by volkovasystems** [comment]
there's no news in bower that they are obsolete plus the last commit was nov 8, 2016, I want to know where did you get that info.

**Comment by ericelliott** [comment]
Compare that commit activity to 2 years ago. Compare currently "active" maintainers to the early project maintainers. The early maintainers have long since left the project.

Bower [never gained the momentum of npm](http://www.modulecounts.com/) -- never even came close, and today, most projects are bundling for the front-end using Webpack (some browserify, some rollup).

New projects supporting Bower are rare. Old projects dropping Bower support are common. TypeScript, currently the most popular compile-to-JS solution doesn't even mention Bower in its [build tool integration docs](https://www.typescriptlang.org/docs/handbook/integrating-with-build-tools.html).

Likewise, many of the most popular libraries [such as Lodash](https://lodash.com/) no longer mention Bower install in their docs.

The writing is on the wall for Bower. I wouldn't use it for new projects, and I'd start to migrate legacy projects if they require frequent, ongoing maintenance.

**Comment by volkovasystems** [comment]
Sad :(

**Comment by ericelliott** [comment]
Well, there is a version on Bower. Does the bower install work for you? Looks like [~15% of the JS world is still using it](https://twitter.com/_ericelliott/status/818655123895296000).

**Comment by volkovasystems** [comment]
Yes, but I'll monitor bower regarding what you said. Right now, I'm trying to think how we will reconfigure our webpack configurations for all our modules. :smile:
