### ISSUE TITLE
Using cuid in containerized environments

### ISSUE THREAD

**Issue by tynor** [ericelliott/cuid#98]
Hello,

I've been looking at using cuid for a project and I'm wondering if there could be any issue when used in containers.

Namely:

- Inside (our) containers, processes always have the same PID (2, in our case).
- Inside (our) containers of the same service, they always have the same hostname (at least, what's returned by `gethostname(3)` is).

Maybe these are silly questions, but given that the component of cuid comprised of those pieces of information is specifically in place to prevent issues arising from simultaneous process execution, and that containers are often started in parallel (by the dozens in some cases):

1. Would that environment significantly increase the risk of collisions (even if it's still very small)?
2. It looks like the idea of using UUIDs as a part of cuid doesn't seem attractive (based on #19), but would it make sense to replace the client fingerprint as currently calculated with the first four digits of the container ID (which is at least unique within a given cluster)? Or is there some other recommended source of client identity for servers?
3. If it's totally fine for the client fingerprint to be identical between multiple processes (on multiple machines), can it be elided entirely?

Thank you in advance for any insight you can bring!

**Comment by ericelliott** [comment]
> 1. Would that environment significantly increase the risk of collisions (even if it's still very small)?

Yes, and the risk not insignificant. It would be only slightly better than using PSRNG v4 UUIDs, meaning that if you generate lots of ids in the same millisecond, chances of collision could realistically be as high as 1 in a million. In a large, distributed system processing tens or hundreds of millions of entities daily, that's not an acceptable level.

If you only generate dozens of entities per day, and the stakes are low if a collision does happen, maybe that's acceptable risk. I wouldn't do it.

> It looks like the idea of using UUIDs as a part of cuid doesn't seem attractive

No, because of the [birthday paradox](https://en.wikipedia.org/wiki/Birthday_problem), and the lack other additional entropy, UUID is more collision-prone than cuid, perhaps even without the fingerprint (because cuid features a session counter that will likely diverge as instances start generating ids independent of each other). V4 UUID is just a pseudo-random number. cuid already contains a pseudo-random component out of the box, so adding V4 UUID to it would not significantly improve its strength.

People who tell you a random number guarantees against collision seem to be unaware of the birthday paradox, or simply lack real life experience with V4 UUIDs at massive scale. As collections grow, the ability for randomness to guarantee uniqueness decreases. In other words, as `n` rises linearly, the probability of collision `p` rises exponentially:

<img width="525" alt="screen shot 2018-02-25 at 7 47 13 pm" src="https://user-images.githubusercontent.com/364727/36652625-c334090a-1a64-11e8-80c0-d7a58af98a43.png">

I think it may be time to introduce a way to take a function to generate the client fingerprint, considering all the different contexts people are using cuid in today.

Maybe we can export a universal `cuidFactory` function with the following signature:

```js
cuidFactory = (getClientFingerPrint: () => String) => () => CuidString
```

In your case, getClientFingerprint could simply return a container id substring.

**Comment by tynor** [comment]
Thanks for the response!

I definitely agree that a 1 in 1-million chance of collision is extremely risky.

I'm not working with the JS version of cuid (nor am I very familiar with JS), so I probably wouldn't be the one to make a PR out of it.

Thank you, again. Cuid (with the change in client fingerprint generation) definitely looks like the best option in the field for this case.
